In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score

## Build the network (model)

In [2]:
model = Sequential()
model.add(Dense(50, input_dim=4, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 51        
Total params: 2,851
Trainable params: 2,851
Non-trainable params: 0
_________________________________________________________________


## Load data (and remove one class)

In [4]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
data = data.drop(data[data.iris=='Iris-virginica'].index)
print("Rows after removal of 'Iris-virginica':",len(data))

Rows: 150
Rows after removal of 'Iris-virginica': 100


## Prepare samples and labels

In [5]:
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4]
samples = samples.astype(float)
labels = data.to_numpy()[:,4]

labels[labels[:]=='Iris-versicolor']=0
labels[labels[:]=='Iris-setosa']=1
#labels[labels[:]=='Iris-virginica']=2
labels = labels.astype(float)
print("Classes after renaming:",set(labels))

print("Samples:",samples.shape)
print("Labels:",labels.shape)


Classes: {'Iris-setosa', 'Iris-versicolor'}
Classes after renaming: {0.0, 1.0}
Samples: (100, 4)
Labels: (100,)


## Compile and fit model

In [6]:
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=1)

model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])

In [9]:
H = model.fit(trainSamples, trainLabels, epochs=5,batch_size=10)    

Epoch 1/5
8/8 [==============================] - 0s 1ms/step - loss: 0.5585 - accuracy: 1.0000
Epoch 2/5
8/8 [==============================] - 0s 750us/step - loss: 0.5392 - accuracy: 0.9867
Epoch 3/5
8/8 [==============================] - 0s 875us/step - loss: 0.5193 - accuracy: 0.9867
Epoch 4/5
8/8 [==============================] - 0s 1ms/step - loss: 0.4965 - accuracy: 0.9867
Epoch 5/5
8/8 [==============================] - 0s 2ms/step - loss: 0.4784 - accuracy: 1.0000


## Evaluate model

In [10]:
testResults = model.predict(testSamples)
testResults = (testResults*2).astype(dtype=int) #conversion to (0,1)
print(testResults.T)
print(confusion_matrix(testLabels, testResults))
print(classification_report(testLabels, testResults))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels, testResults)))
print("Accuracy: ",accuracy_score(testLabels, testResults))


[[0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1]]
[[15  0]
 [ 0 10]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        15
         1.0       1.00      1.00      1.00        10

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

Cohen's Kappa: 1.0
Accuracy:  1.0


# Dataset with three classes

In [11]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4] 
labels = data.to_numpy()[:,4]
samples = samples.astype(float)

labels[labels[:]=='Iris-versicolor']=0
labels[labels[:]=='Iris-setosa']=1
labels[labels[:]=='Iris-virginica']=2
labels = labels.astype(float)

print("Samples:",samples.shape)
print("Labels:",labels.shape)

Rows: 150
Classes: {'Iris-virginica', 'Iris-versicolor', 'Iris-setosa'}
Samples: (150, 4)
Labels: (150,)


In [12]:
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels)

In [13]:
model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])
#model.compile(loss='sparse_categorical_crossentropy', optimizer="adam",metrics=['accuracy'])
#model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [17]:
H = model.fit(trainSamples, trainLabels, epochs=10,batch_size=10)    

Epoch 1/10
12/12 [==============================] - 0s 2ms/step - loss: -0.0431 - accuracy: 0.3482
Epoch 2/10
12/12 [==============================] - 0s 2ms/step - loss: -0.0456 - accuracy: 0.3482
Epoch 3/10
12/12 [==============================] - 0s 3ms/step - loss: -0.0496 - accuracy: 0.3482
Epoch 4/10
12/12 [==============================] - 0s 3ms/step - loss: -0.0517 - accuracy: 0.3482
Epoch 5/10
12/12 [==============================] - 0s 3ms/step - loss: -0.0564 - accuracy: 0.3482
Epoch 6/10
12/12 [==============================] - 0s 4ms/step - loss: -0.0586 - accuracy: 0.3482
Epoch 7/10
12/12 [==============================] - 0s 3ms/step - loss: -0.0634 - accuracy: 0.3482
Epoch 8/10
12/12 [==============================] - 0s 3ms/step - loss: -0.0656 - accuracy: 0.3482
Epoch 9/10
12/12 [==============================] - 0s 2ms/step - loss: -0.0717 - accuracy: 0.3482
Epoch 10/10
12/12 [==============================] - 0s 3ms/step - loss: -0.0729 - accuracy: 0.3482


## Evaluate model

In [18]:
testResults = model.predict(testSamples)
testResults = (testResults*2).astype(dtype=int) #conversion to (0,1)
print(testResults.T)
print(confusion_matrix(testLabels, testResults))
print(classification_report(testLabels, testResults))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels, testResults)))
print("Accuracy: ",accuracy_score(testLabels, testResults))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1]]
[[ 0 14  0]
 [ 0 11  0]
 [ 0 13  0]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        14
         1.0       0.29      1.00      0.45        11
         2.0       0.00      0.00      0.00        13

    accuracy                           0.29        38
   macro avg       0.10      0.33      0.15        38
weighted avg       0.08      0.29      0.13        38

Cohen's Kappa: 0.0
Accuracy:  0.2894736842105263


What is the problem?
The output is a number - no way that ANN learns the proper output!

## Change to one-hot encoding

In [19]:
print(labels.shape)
labels = tf.keras.utils.to_categorical(labels)
print(labels.shape)

(150,)
(150, 3)


## New model (output: vector of 3 values)

In [20]:
model = Sequential()
model.add(Dense(50, input_dim=4, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
#model.add(Dense(1, activation='sigmoid'))
#model.add(Dense(3, activation='sigmoid')) # three values
model.add(Dense(3, activation='softmax')) # three values and normalization (output sums to 1)

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 50)                250       
_________________________________________________________________
dense_4 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 153       
Total params: 2,953
Trainable params: 2,953
Non-trainable params: 0
_________________________________________________________________


### Train model

In [21]:
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=1)
#model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [24]:
H = model.fit(trainSamples, trainLabels, epochs=10,batch_size=10, validation_data=(testSamples,testLabels))    

Epoch 1/10
12/12 [==============================] - 0s 10ms/step - loss: 0.5175 - accuracy: 0.8125 - val_loss: 0.5273 - val_accuracy: 0.6842
Epoch 2/10
12/12 [==============================] - 0s 5ms/step - loss: 0.4998 - accuracy: 0.8214 - val_loss: 0.5224 - val_accuracy: 0.6316
Epoch 3/10
12/12 [==============================] - 0s 5ms/step - loss: 0.4851 - accuracy: 0.8214 - val_loss: 0.5040 - val_accuracy: 0.6842
Epoch 4/10
12/12 [==============================] - 0s 4ms/step - loss: 0.4709 - accuracy: 0.7857 - val_loss: 0.5026 - val_accuracy: 0.6316
Epoch 5/10
12/12 [==============================] - 0s 6ms/step - loss: 0.4620 - accuracy: 0.8393 - val_loss: 0.4733 - val_accuracy: 0.7632
Epoch 6/10
12/12 [==============================] - 0s 4ms/step - loss: 0.4457 - accuracy: 0.8750 - val_loss: 0.4643 - val_accuracy: 0.7632
Epoch 7/10
12/12 [==============================] - 0s 4ms/step - loss: 0.4350 - accuracy: 0.8750 - val_loss: 0.4479 - val_accuracy: 0.8158
Epoch 8/10
12/12 [=

### Evaluate model (it is one-hot encoded!)

In [13]:
testResults = model.predict(testSamples)
print(testResults)
print(testResults.argmax(axis=1))

print(confusion_matrix(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print(classification_report(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels.argmax(axis=1), testResults.argmax(axis=1))))
print("Accuracy: ",accuracy_score(testLabels.argmax(axis=1), testResults.argmax(axis=1)))


[[0.40282774]
 [0.36920965]
 [0.66562223]
 [0.41259152]
 [0.43908626]
 [0.64592314]
 [0.65072393]
 [0.39889738]
 [0.39919817]
 [0.36968005]
 [0.39081076]
 [0.6410374 ]
 [0.3572889 ]
 [0.3432365 ]
 [0.3663659 ]
 [0.6662994 ]
 [0.62503636]
 [0.6157006 ]
 [0.3616761 ]
 [0.6452378 ]
 [0.6558031 ]
 [0.35942048]
 [0.37656087]
 [0.38609242]
 [0.64861643]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


AxisError: axis 1 is out of bounds for array of dimension 1

In [14]:
sample = [[1,2,3,4]]
pred = model.predict(sample)
print(sample,'->',pred)

pred = model.predict(testSamples[10:14])
for p,t in zip(pred[0:4],testLabels[10:14]):
    print(p,"->",t)


[[1, 2, 3, 4]] -> [[0.39046293]]
[0.39081076] -> 0.0
[0.6410374] -> 1.0
[0.3572889] -> 0.0
[0.3432365] -> 0.0


In [12]:
model.save('iris.h5')