In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score

## Build the network (model)

In [2]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4] 
labels = data.to_numpy()[:,4]
samples = samples.astype(float)

labels[labels[:]=='Iris-versicolor']=0
labels[labels[:]=='Iris-setosa']=1
labels[labels[:]=='Iris-virginica']=2
labels = labels.astype(float)

print("Samples:",samples.shape)
print("Labels:",labels.shape)

Rows: 150
Classes: {'Iris-setosa', 'Iris-virginica', 'Iris-versicolor'}
Samples: (150, 4)
Labels: (150,)


## Change to one-hot encoding

In [3]:
print(labels.shape)
labels = tf.keras.utils.to_categorical(labels)
print(labels.shape)

(150,)
(150, 3)


## New model (output: vector of 3 values)

In [4]:
model = Sequential()
model.add(Dense(50, input_dim=4, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(3, activation='softmax')) # three values and normalization (output sums to 1)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 153       
Total params: 2,953
Trainable params: 2,953
Non-trainable params: 0
_________________________________________________________________


### Train model

In [5]:
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=1)
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [8]:
H = model.fit(trainSamples, trainLabels, epochs=10,batch_size=10, validation_data=(testSamples,testLabels))    

Epoch 1/10
12/12 [==============================] - 0s 4ms/step - loss: 0.5077 - accuracy: 0.7857 - val_loss: 0.5249 - val_accuracy: 0.6579
Epoch 2/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4946 - accuracy: 0.8750 - val_loss: 0.4980 - val_accuracy: 0.7895
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4785 - accuracy: 0.8482 - val_loss: 0.4982 - val_accuracy: 0.6842
Epoch 4/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4638 - accuracy: 0.8661 - val_loss: 0.4768 - val_accuracy: 0.7632
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4503 - accuracy: 0.8839 - val_loss: 0.4599 - val_accuracy: 0.8158
Epoch 6/10
12/12 [==============================] - 0s 3ms/step - loss: 0.4405 - accuracy: 0.9107 - val_loss: 0.4446 - val_accuracy: 0.9474
Epoch 7/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4285 - accuracy: 0.9196 - val_loss: 0.4404 - val_accuracy: 0.8158
Epoch 8/10
12/12 [==

### Evaluate model (it is one-hot encoded!)

In [9]:
testResults = model.predict(testSamples)
print(testResults)
print(testResults.argmax(axis=1))

print(confusion_matrix(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print(classification_report(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels.argmax(axis=1), testResults.argmax(axis=1))))
print("Accuracy: ",accuracy_score(testLabels.argmax(axis=1), testResults.argmax(axis=1)))


[[0.03362826 0.96403205 0.00233973]
 [0.5341833  0.2646086  0.201208  ]
 [0.5189156  0.06004384 0.4210406 ]
 [0.04380843 0.9528041  0.00338749]
 [0.3288432  0.00880919 0.66234756]
 [0.48147875 0.04013814 0.4783831 ]
 [0.3670602  0.0129989  0.6199409 ]
 [0.07673793 0.9158556  0.00740645]
 [0.06920869 0.9244731  0.00631823]
 [0.32398215 0.00847278 0.667545  ]
 [0.52107584 0.06185539 0.41706875]
 [0.0601845  0.9345522  0.00526336]
 [0.3188116  0.00791353 0.6732749 ]
 [0.50762737 0.05332122 0.4390514 ]
 [0.48643994 0.04165497 0.47190508]
 [0.05438267 0.94109666 0.00452066]
 [0.5433592  0.08422643 0.3724144 ]
 [0.487672   0.04277911 0.4695489 ]
 [0.06528312 0.928862   0.00585495]
 [0.04869675 0.9474359  0.00386727]
 [0.5061404  0.05098316 0.44287637]
 [0.48558122 0.04199494 0.47242382]
 [0.4271477  0.0227481  0.55010426]
 [0.04952872 0.9464837  0.00398759]
 [0.34328407 0.01004782 0.6466682 ]
 [0.535067   0.07551041 0.38942254]
 [0.03593498 0.9614936  0.00257141]
 [0.05023856 0.94568044 0.00

In [10]:
model.save('iris_model')

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: iris_model\assets
